name: Generate XML Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate Sitemap
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Sitemap
        run: |
          npx sitemap-generator-cli https://tegar-izo.github.io/ --filepath ./sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "auto: update sitemap.xml [skip ci]" || exit 0
          git push
